name: Release

on:
  release:
    types: [published]

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'unstoppablecarl/vue-pane'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm publish --access public --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
